### ISSUE TITLE
Help with Xavier Setup Step #8

### ISSUE THREAD

**Issue by tonydav41** [tevora-threat/Scout#15]
I am new to Ubuntu, so please forgive me if this is a stupid question. But I am stuck on Step 8 (Copy the files in scripts/Xavier/l4t-usb-device-mode over to /opt/nvidia/l4t-usb-device-mode/)

When I type cp -b scripts/Xavier/l4t-usb-device-mode /opt/nvidia/l4t-usb-device-mode/

I get this error message:

cp: cannot stat '/scripts/Xavier/l4t-usb-device-mode': No such file or directory

Can you tell me what I need to type in Terminal to complete step 8? Thanks!

**Comment by trumankain** [comment]
It's not a stupid question. Thank you for checking out the project.
`cd scripts/Xavier/l4t-usb-device-mode`
`cp * /opt/nvidia/l4t-usb-device-mode/.`

**Comment by tonydav41** [comment]
Thank you!

**Comment by darkstar939** [comment]
Is the gui coming any time soon?


Sent from Yahoo Mail for iPhone


On Sunday, September 22, 2019, 3:00 PM, tonydav41 <notifications@github.com> wrote:


Thank you!
