### ISSUE TITLE
Detecting stolen vehicles 

### ISSUE THREAD

**Issue by icepicknz** [tevora-threat/Scout#2]
I'd love to be able to be reported of cars that are stolen or have amber alerts on them.

A list can be downloaded for New Zealand from https://www.police.govt.nz/stolenwanted/stolen-vehicles?nondesktop (download CSV). How easy would something like this be to implement? I'd love for an easy way to prepackage units and ship at cost to our Tesla Owners group of New Zealand.

Would also be cool to have a second database of Tesla Owners Group members, so when they drive past it shows up the name of the person who just drove past, would be a cool gimmick and a talking point when seeing members at a meetup.

**Comment by danibjor** [comment]
When you first have the plate number from the video, it’s easy to cross check that to a list.

**Comment by icepicknz** [comment]
I've ordered the Jetson for my car so I can do realtime; however for now I have a rpi4 and wonder if I can start testing and playing. The readme said the webui instructions would come in 24hrs, I wonder when the other instructions for reading the video data and capturing the plate data to database would be available.

Would be nice to have a complete step by step guide for rPi and Jetson, but beggars can't be choosers :)

**Comment by danibjor** [comment]
There is a whole lot missing on this repo. They probably have some work to do, to clean up the code etc before uploading. Until then, we would just have to wait. There is not much we can do with what's available right now.

**Comment by mikenewhouse** [comment]
Does not appear to be much more out of Scout in the past week or so. Waiting to see if there are any update from anyone before moving forward. Tesla my have shut this down for some reason.

**Comment by mikenewhouse** [comment]
@danibjor - Can you elaborate a little on what parts are missing?

**Comment by mikenewhouse** [comment]
@trumankain - are you out there?

**Comment by danibjor** [comment]
@mikenewhouse everything is missing at the moment (all but a script to log car location). Right now it's just a repo with links to projects that they use. All the code that builds on top of the said/listed projects to tie this together to what we see in the video is missing.

**Comment by trumankain** [comment]
Thank you all for your interest in the project. For some reasons I won't detail here the full code release has been delayed slightly. Rest assured, I will commit everything shown in the demo up to the repo as soon as I am able to.

To address OP's issue, it's unlikely at this time that I will implement an integration specifically for stolen plate detections, however @danibjor is correct in that this would be a trivial feature to add in if you wanted to.

Thanks again for all of the support and interest in the project, I'm really pushing to get everything released by this weekend at the latest.
