### ISSUE TITLE
disk not mounting across to Mac 

### ISSUE THREAD

**Issue by icepicknz** [tevora-threat/Scout#3]
So my gear arrived today and I've set it all up.

Unfortunately the disk is not sharing across to my MAC when I start the script

```
root@jetson-0423818076546:/opt/nvidia/l4t-usb-device-mode# ls
mac-addresses  nv-l4t-usb-device-mode-config.sh  nv-l4t-usb-device-mode-start.sh

root@jetson-0423818076546:/opt/nvidia/l4t-usb-device-mode# cat mac-addresses 
mac_rndis_h=5a:d0:de:22:e7:1c
mac_rndis_d=5a:d0:de:22:e7:1d
mac_ecm_h=5a:d0:de:22:e7:1e
mac_ecm_d=5a:d0:de:22:e7:1f

```

I have since gone ahead, created the other 284gb and 500gb disks, done an image of the 240gbps disks to sdsusb.img, updated the files as requested, but still no go.

`root@jetson-0423818076546:/opt/nvidia/l4t-usb-device-mode# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        28G  7.9G   19G  31% /
devtmpfs        7.7G     0  7.7G   0% /dev
tmpfs           7.8G  4.0K  7.8G   1% /dev/shm
tmpfs           7.8G   29M  7.7G   1% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup
/dev/nvme0n1p2  260G  224G   23G  91% /teslaflash
/dev/nvme0n1p3  458G   73M  435G   1% /tesladrive
tmpfs           1.6G  128K  1.6G   1% /run/user/1001
`

**Comment by mikenewhouse** [comment]
@icepicknz - That is unfortunate to hear, I had all the gear in my cart and paused on the buy button for just this reason. Sorry to hear.
It appears that @trumankain has checked out, he maybe busy since he is now on every media outlet but it sucks that he posted it was ready and try it and then that not be true. Make's you think that maybe it was a hoax....

**Comment by trumankain** [comment]
Thank you for opening this issue. I'm working on a detailed setup wiki that will address setup first for the Jetson devices, then shortly afterward for Pi devices. Jetson wiki should be posted by this weekend. I appreciate your patience!

**Comment by mikenewhouse** [comment]
@trumankain - awesome to hear you are still with us, I am sure I am not the only one excited to try and test your project. I look forward to the updates and THANK YOU.

**Comment by icepicknz** [comment]
Got this working properly, my Xavier was new and didn't have all the jetpack modules installed. Reinstalled using Jetpack rather than the software it came with and it resolved the USB drive issue... slowly getting there

**Comment by icepicknz** [comment]
I was premature; so it worked in 4.2 out the box, but 4.2 doesn't support TensorFlow with python 2.7 so I have reverted back to 4.1.1 and the disk is not mounting again, no errors, the interface comes up as per below, but doesn't connect to host or show a mounted disk

l4tbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.55.1  netmask 255.255.255.0  broadcast 192.168.55.255

**Comment by icepicknz** [comment]
```
Aug 25 10:08:03 jetson-0423818076546 kernel: [ 1245.042581] ucsi_ccg 1-0008: port0 evt: Type-C Port Connect Detected
Aug 25 10:08:03 jetson-0423818076546 kernel: [ 1245.044650] ucsi_ccg 1-0008: [typec-port0] Cable state:1, cable id:2
Aug 25 10:08:03 jetson-0423818076546 kernel: [ 1245.379871] usb 1-1: new low-speed USB device number 11 using tegra-xusb
Aug 25 10:08:03 jetson-0423818076546 kernel: [ 1245.381588] usb 1-1: Device not responding to setup address.
Aug 25 10:08:04 jetson-0423818076546 kernel: [ 1245.589509] usb 1-1: Device not responding to setup address.
Aug 25 10:08:04 jetson-0423818076546 kernel: [ 1245.795798] usb 1-1: device not accepting address 11, error -71
Aug 25 10:08:04 jetson-0423818076546 kernel: [ 1245.915881] usb 1-1: new low-speed USB device number 12 using tegra-xusb
Aug 25 10:08:04 jetson-0423818076546 kernel: [ 1245.917561] usb 1-1: Device not responding to setup address.
Aug 25 10:08:04 jetson-0423818076546 kernel: [ 1246.124551] usb 1-1: Device not responding to setup address.
Aug 25 10:08:04 jetson-0423818076546 kernel: [ 1246.331897] usb 1-1: device not accepting address 12, error -71
Aug 25 10:08:04 jetson-0423818076546 kernel: [ 1246.332336] usb usb1-port1: attempt power cycle
Aug 25 10:08:05 jetson-0423818076546 kernel: [ 1246.767688] usb 1-1: new low-speed USB device number 13 using tegra-xusb
Aug 25 10:08:05 jetson-0423818076546 kernel: [ 1246.912290] usb 1-1: No LPM exit latency info found, disabling LPM.
Aug 25 10:08:05 jetson-0423818076546 kernel: [ 1246.919325] usb 1-1: New USB device found, idVendor=05ac, idProduct=7300
Aug 25 10:08:05 jetson-0423818076546 kernel: [ 1246.919339] usb 1-1: New USB device strings: Mfr=2, Product=3, SerialNumber=1
Aug 25 10:08:05 jetson-0423818076546 kernel: [ 1246.919346] usb 1-1: Product: Macintosh
Aug 25 10:08:05 jetson-0423818076546 kernel: [ 1246.919352] usb 1-1: Manufacturer: Apple Inc.
Aug 25 10:08:05 jetson-0423818076546 kernel: [ 1246.919355] usb 1-1: SerialNumber: 7C2BAB0E15E8E8969B4103B0CC1674AA

```

**Comment by icepicknz** [comment]
reinstalled for like a 10th time and git it working on 4.2 Jetson
