### ISSUE TITLE
EXT4 on Mac?

### ISSUE THREAD

**Issue by icepicknz** [tevora-threat/Scout#6]
So I finally managed to Jetpack upgrade my Xavier and have the l4t-usb-device  working and started from scratch with your how to.

The part that says "Once you see the drive come up on your Windows or Mac, reformat it (from said Windows/Mac) as EXT4", EXT4 is not an option with MAC? So I plugged it into my Jetpack ubuntu host (which I bought today as I couldn't get jetpack working through virtual box) and formatted the partition as EXT4 as described.

Problem now is Ubuntu doesn't want to make an image of the file, worked fine previously for me, but I think that's because I didn't have an EXT4 partition inside an EXT4 partition, it says Creating disk image: 0.0% but doesn't increase what so ever. Not mounted and trying to save the image to the 284Gb disk. I see the file appear , so it reserves the disk space, but doesn't progress.

Going to try a few other options and will report back

**Comment by icepicknz** [comment]
running jetpack 4.2 by the way; tried a few reboots, deleting partitions and trying again etc, no go... I will see if dd works

**Comment by icepicknz** [comment]
sorted via CLI, just took a along time and GUI wasn't giving any updates

icepick@ubuntu-xavier:~$ sudo dd if=/dev/nvme0n1p1 of=/media/icepick/disk2/sdsusb.img
[sudo] password for icepick: 
Sorry, try again.
[sudo] password for icepick: 
468750336+0 records in
468750336+0 records out
240000172032 bytes (240 GB, 224 GiB) copied, 3879.57 s, 61.9 MB/s

**Comment by tonydav41** [comment]
hey @icepicknz would you mind sharing how you got the ssd to show up on your mac or windows computer to reformat? Did you flash the SSD after breaking off the partition? I flashed the Xavier with Jetpack during initial setup, but not the SSD. I'm about to bang my head against the wall lol

**Comment by icepicknz** [comment]
Sorry I'm travelling for the next 2 weeks and to be honest shelved the project after spending a crap load on the Xavier and the smaller box hoping this project was moving forward.

I'll have to have a look when I get Home, but to be honest I don't believe this project is going anywhere
